import './styles.css';
import './system-fonts.css';
import './responsive.css';
import { DEFAULT_CAMERA, DEMO, LIMITS, buildMesh, columns, download, fitView, meshToGLB, meshToOBJ, parseCSV, parseJSON, parseProject, profile, resizeCamera } from './core.js';

const app = document.querySelector('#app');
const initialSettings = { x: 'minute', y: 'tide_m', z: 'energy', radius: 'salinity_psu', color: 'tide_m' };
let state = { dataset: structuredClone(DEMO), settings: { ...initialSettings }, camera: { ...DEFAULT_CAMERA }, history: [], status: 'Ready to sculpt', importToken: 0 };
let mesh = buildMesh(state.dataset.data, state.settings), canvas, ctx;

function esc(s) { return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
function fmt(n) { return Number.isFinite(n) ? Number(n).toLocaleString(undefined, { maximumFractionDigits: 3 }) : '—'; }
function options(selected, fields) { return fields.map(f => `<option ${f === selected ? 'selected' : ''} value="${esc(f)}">${esc(f)}</option>`).join(''); }

function render() {
  const fields = columns(state.dataset.data), rows = state.dataset.data, stats = fields.map(f => profile(rows, f));
  app.innerHTML = `<header class="topbar"><div class="brand"><span class="mark">✦</span><div><strong>DATA SCULPTURE</strong><small>make the invisible tactile</small></div></div><div class="top-actions"><button class="ghost" id="undoBtn" ${state.history.length ? '' : 'disabled'}>Undo</button><button class="ghost" id="newBtn">New</button><label class="button ghost">Import <input id="fileInput" type="file" accept=".csv,.json,.dsproj,application/json,text/csv" hidden></label><button class="primary" id="saveBtn">Save project</button></div></header>
  <main class="workspace"><aside class="sidebar left"><section class="panel intro"><div class="eyebrow">01 · SOURCE</div><h1>${esc(state.dataset.name)}</h1><p>${esc(state.dataset.description || 'Local data, shaped into a navigable object.')}</p><div class="chip-row"><span class="chip">${rows.length} rows</span><span class="chip">${fields.length} fields</span><span class="chip good">LOCAL ONLY</span></div></section>
  <section class="panel"><div class="section-title"><span>Data health</span><span class="status-dot"></span></div><div class="health-grid"><div><b>${rows.length}</b><small>observations</small></div><div><b>${stats.reduce((a, s) => a + s.missing, 0)}</b><small>null / text gaps</small></div><div><b>${stats.reduce((a, s) => a + s.extreme, 0)}</b><small>extreme flags</small></div></div><div class="table-wrap"><table><thead><tr><th>FIELD</th><th>TYPE</th><th>RANGE / VALUES</th></tr></thead><tbody>${stats.map(s => `<tr><td>${esc(s.field)}</td><td><span class="type">${s.numeric === s.count ? 'NUM' : s.categories <= 8 ? 'TEXT' : 'MIXED'}</span></td><td>${s.numeric ? `${fmt(s.min)} → ${fmt(s.max)}` : `${s.categories} values`}${s.missing ? ` <em>${s.missing} missing</em>` : ''}${s.extreme ? ` <em class="warn">${s.extreme} extreme</em>` : ''}</td></tr>`).join('')}</tbody></table></div><p class="hint">Nothing is silently dropped. Missing coordinates use the midpoint and are marked amber in the sculpture.</p></section>
  <section class="panel provenance"><div class="section-title">Provenance <span class="lock">⌁ local</span></div><p><b>${esc(state.dataset.name)}</b><br><span class="muted">synthetic / user-supplied · never uploaded</span></p><div class="mini-line"><span>Parser</span><span>bounded CSV / JSON</span></div><div class="mini-line"><span>Limits</span><span>${(LIMITS.bytes / 1e6).toFixed(0)} MB · ${LIMITS.rows.toLocaleString()} rows</span></div><button class="text-button" id="reattachBtn">Reattach local data ↗</button></section></aside>
  <section class="stage"><div class="stage-head"><div><div class="eyebrow">LIVE FORM / ${rows.length} POINTS</div><h2>Every value leaves a trace.</h2></div><div class="stage-tools"><button class="icon-btn" id="fitBtn" title="Fit sculpture">⛶</button><button class="icon-btn" id="resetViewBtn" title="Reset view">↺</button></div></div><div class="canvas-shell"><canvas id="sculpture" aria-label="Interactive 3D data sculpture"></canvas><div class="canvas-label top-left">DRAG TO ORBIT<br><span>SCROLL TO ZOOM</span></div><div class="canvas-label bottom-right"><span class="legend-dot"></span> normal <span class="legend-dot amber"></span> missing</div><div class="render-badge">● LIVE MESH <span>${mesh.triangleCount.toLocaleString()} tris</span></div></div><div class="stage-foot"><span id="status">${esc(state.status)}</span><span>local computation · no upload</span></div></section>
  <aside class="sidebar right"><section class="panel mapping"><div class="eyebrow">02 · MAPPING</div><h3>Give dimensions a meaning.</h3><p class="muted">Change a field and watch the form respond.</p>${mappingControl('X axis · length', 'x', state.settings.x, fields, '↔')}${mappingControl('Y axis · lift', 'y', state.settings.y, fields, '↕')}${mappingControl('Z axis · depth', 'z', state.settings.z, fields, '◈')}${mappingControl('Radius · volume', 'radius', state.settings.radius, fields, '◉')}${mappingControl('Color · hue', 'color', state.settings.color, fields, '●')}<div class="mapping-note">${mappingSummary()}</div></section><section class="panel composition"><div class="eyebrow">03 · COMPOSITION</div><h3>Frame the story.</h3><div class="control-row"><label>Projection<select id="projection"><option>Perspective</option><option>Orthographic</option></select></label><label>Sequence<select id="sequence"><option>Row order</option><option>Time →</option></select></label></div><div class="camera-buttons"><button class="ghost" data-camera="left">←</button><button class="ghost" data-camera="up">↑</button><button class="ghost" data-camera="down">↓</button><button class="ghost" data-camera="right">→</button></div></section><section class="panel exports"><div class="eyebrow">04 · TAKE IT WITH YOU</div><h3>Export a useful object.</h3><div class="export-grid"><button class="export-btn" id="glbBtn"><b>GLB</b><small>mesh + colors</small></button><button class="export-btn" id="objBtn"><b>OBJ</b><small>universal mesh</small></button><button class="export-btn" id="pngBtn"><b>PNG</b><small>framed image</small></button><button class="export-btn" id="mapBtn"><b>MAP</b><small>explanation</small></button></div><p class="hint">GLB includes vertex colors, normals and mapping provenance. OBJ is paired with a human-readable MAP file.</p></section></aside></main>`;
  canvas = document.querySelector('#sculpture'); ctx = canvas.getContext('2d'); wireCanvas(); bind(); draw();
}

function mappingControl(label, key, value, fields, icon) { return `<label class="map-control"><span class="map-icon">${icon}</span><span>${label}<select data-map="${key}">${options(value, fields)}</select></span></label>`; }
function mappingSummary() { return `<b>${esc(state.settings.x)}</b> stretches left → right · <b>${esc(state.settings.y)}</b> lifts the form · <b>${esc(state.settings.color)}</b> drives color.`; }
function settingsFor(data, preferred) { const fields = columns(data); const pick = (key, index) => fields.includes(preferred[key]) ? preferred[key] : fields[Math.min(index, fields.length - 1)]; return { ...preferred, x: pick('x', 0), y: pick('y', 1), z: pick('z', 2), radius: pick('radius', 0), color: pick('color', 1) }; }
function wireCanvas() { const rect = canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2); canvas.width = Math.max(1, rect.width * dpr); canvas.height = Math.max(1, rect.height * dpr); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }
function bind() {
  document.querySelectorAll('[data-map]').forEach(el => el.addEventListener('change', e => { const candidateSettings = { ...state.settings, [e.target.dataset.map]: e.target.value }; let candidateMesh; try { candidateMesh = buildMesh(state.dataset.data, candidateSettings); } catch (err) { setStatus(`Mapping failed: ${err.message}`); return; } const candidateCamera = resizeCamera(candidateMesh, canvas.clientWidth, canvas.clientHeight, state.camera); pushHistory(); state.settings = candidateSettings; state.camera = candidateCamera; mesh = candidateMesh; setStatus(`Mapped ${e.target.value} to ${e.target.dataset.map}.`); draw(); render(); }));
  document.querySelectorAll('[data-camera]').forEach(el => el.addEventListener('click', () => { invalidateImports(); const d = el.dataset.camera; state.camera.yaw += d === 'left' ? -.22 : d === 'right' ? .22 : 0; state.camera.pitch += d === 'up' ? .16 : d === 'down' ? -.16 : 0; state.camera.panX = 0; state.camera.panY = 0; state.camera.fitIntent = false; draw(); }));
  document.querySelector('#fitBtn').onclick = () => { invalidateImports(); Object.assign(state.camera, fitView(mesh, canvas.clientWidth, canvas.clientHeight, state.camera), { fitIntent: true }); draw(); setStatus('Camera fitted to the full sculpture with padding.'); };
  document.querySelector('#resetViewBtn').onclick = () => { invalidateImports(); state.camera = { ...DEFAULT_CAMERA }; draw(); };
  document.querySelector('#undoBtn').onclick = undo;
  document.querySelector('#newBtn').onclick = () => { if (!confirm('Start a new sculpture? Choose Cancel or press Escape to keep this work.')) return; pushHistory(); state.dataset = structuredClone(DEMO); state.settings = { ...initialSettings }; mesh = buildMesh(state.dataset.data, state.settings); setStatus('New sculpture opened.'); render(); };
  document.querySelector('#saveBtn').onclick = saveProject;
  document.querySelector('#glbBtn').onclick = () => { download(meshToGLB(mesh, metadata()), 'data-sculpture.glb'); setStatus('GLB download started.'); };
  document.querySelector('#objBtn').onclick = () => { download(new Blob([meshToOBJ(mesh)], { type: 'text/plain' }), 'data-sculpture.obj'); setStatus('OBJ download started. Use MAP for its explanation.'); };
  document.querySelector('#pngBtn').onclick = () => { draw(); try { canvas.toBlob(blob => { if (!blob || !blob.size) return setStatus('PNG export failed: the browser returned no image bytes.'); try { download(blob, 'data-sculpture.png'); setStatus('PNG download started. Check your downloads.'); } catch (err) { setStatus(`PNG export failed: ${err.message}`); } }, 'image/png'); } catch (err) { setStatus(`PNG export failed: ${err.message}`); } };
  document.querySelector('#mapBtn').onclick = () => { download(new Blob([mappingText()], { type: 'text/plain' }), 'data-sculpture-map.txt'); setStatus('MAP download started.'); };
  document.querySelector('#fileInput').onchange = e => importFile(e.target.files[0]); document.querySelector('#reattachBtn').onclick = () => document.querySelector('#fileInput').click();
  let drag = false, last = [0, 0]; canvas.onpointerdown = e => { drag = true; last = [e.clientX, e.clientY]; canvas.setPointerCapture(e.pointerId); }; canvas.onpointerup = () => drag = false; canvas.onpointermove = e => { if (!drag) return; invalidateImports(); state.camera.yaw += (e.clientX - last[0]) * .008; state.camera.pitch = Math.max(-1.1, Math.min(1.1, state.camera.pitch + (e.clientY - last[1]) * .008)); state.camera.panX = 0; state.camera.panY = 0; state.camera.fitIntent = false; last = [e.clientX, e.clientY]; draw(); }; canvas.onwheel = e => { e.preventDefault(); invalidateImports(); state.camera.panX = 0; state.camera.panY = 0; state.camera.fitIntent = false; state.camera.zoom = Math.max(.55, Math.min(1.7, state.camera.zoom * (e.deltaY > 0 ? .94 : 1.06))); draw(); };
  window.onresize = () => { wireCanvas(); Object.assign(state.camera, resizeCamera(mesh, canvas.clientWidth, canvas.clientHeight, state.camera)); draw(); };
  window.onkeydown = e => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'z') { e.preventDefault(); undo(); } };
}
function setStatus(text) { state.status = text; const el = document.querySelector('#status'); if (el) el.textContent = text; }
function invalidateImports() { state.importToken++; }
function pushHistory() { invalidateImports(); state.history.push(JSON.stringify({ dataset: state.dataset, settings: state.settings, camera: state.camera })); if (state.history.length > 30) state.history.shift(); }
function metadata() { return { source: state.dataset.name, rows: state.dataset.data.length, mappings: state.settings, missingPolicy: 'midpoint + amber marker', provenance: 'local data; no upload' }; }
function mappingText() { return `DATA SCULPTURE MAPPING v1\nSource: ${state.dataset.name}\nRows: ${state.dataset.data.length}\n\nX axis (length): ${state.settings.x}\nY axis (lift): ${state.settings.y}\nZ axis (depth): ${state.settings.z}\nRadius (volume): ${state.settings.radius}\nColor (hue): ${state.settings.color}\n\nMissing values: retained in row order, mapped to midpoint, marked amber.\nExtreme values: retained; their range is shown in the editor.\nMesh: ${mesh.pointCount} rings, ${mesh.triangleCount} triangles, vertex normals + colors.\nProvenance: local browser computation; source data is never uploaded.\n`;
}
function saveProject() { const project = { format: 'data-sculpture-project', version: 1, savedAt: new Date().toISOString(), dataset: state.dataset, settings: state.settings, camera: state.camera, metadata: metadata() }; download(new Blob([JSON.stringify(project, null, 2)], { type: 'application/json' }), 'data-sculpture.dsproj'); setStatus('Versioned project saved locally.'); }
async function importFile(file) { if (!file) return; const token = ++state.importToken; if (file.size > LIMITS.bytes) { setStatus(`Import blocked: file exceeds ${LIMITS.bytes / 1e6} MB.`); return; } try { const text = await file.text(); if (token !== state.importToken) return; let incoming, incomingSettings, incomingCamera; if (file.name.endsWith('.dsproj')) { const p = parseProject(text); incoming = p.dataset; incomingSettings = p.settings; incomingCamera = p.camera; } else incoming = file.name.toLowerCase().endsWith('.json') ? parseJSON(text) : parseCSV(text); if (token !== state.importToken) return; if (!incoming.data?.length) throw new Error('No rows found.'); const candidateSettings = settingsFor(incoming.data, incomingSettings || state.settings); const candidateMesh = buildMesh(incoming.data, candidateSettings); const candidateCamera = resizeCamera(candidateMesh, canvas.clientWidth, canvas.clientHeight, incomingCamera || state.camera); if (token !== state.importToken) return; if (!confirm(`Replace the current sculpture with ${file.name}? Choose Cancel or press Escape to keep it.`)) return; if (token !== state.importToken) return; pushHistory(); state.dataset = incoming; state.settings = candidateSettings; state.camera = candidateCamera; mesh = candidateMesh; render(); setStatus(`Imported ${file.name}; ${state.dataset.data.length} rows retained.`); } catch (err) { setStatus(`Import failed: ${err.message}`); } }

function undo() { invalidateImports(); const previous = state.history.pop(); if (!previous) return setStatus('Nothing to undo.'); const restored = JSON.parse(previous); const restoredMesh = buildMesh(restored.dataset.data, restored.settings); const restoredCamera = resizeCamera(restoredMesh, canvas.clientWidth, canvas.clientHeight, restored.camera); state.dataset = restored.dataset; state.settings = restored.settings; state.camera = restoredCamera; mesh = restoredMesh; render(); setStatus('Undid the last change.'); }

function projectPoint(x, y, z) { const cy = Math.cos(state.camera.yaw), sy = Math.sin(state.camera.yaw), cp = Math.cos(state.camera.pitch), sp = Math.sin(state.camera.pitch); const x1 = x * cy - z * sy, z1 = x * sy + z * cy, y1 = y * cp - z1 * sp, z2 = y * sp + z1 * cp; const perspective = 3.8 / (3.8 - z2); return { x: x1 * perspective * state.camera.zoom, y: y1 * perspective * state.camera.zoom, depth: z2 }; }
function draw() { if (!ctx || !mesh) return; const w = canvas.clientWidth, h = canvas.clientHeight, scale = Math.min(w, h) * .27; ctx.clearRect(0, 0, w, h); const gradient = ctx.createRadialGradient(w * .5, h * .4, 0, w * .5, h * .5, Math.max(w, h) * .7); gradient.addColorStop(0, '#192553'); gradient.addColorStop(1, '#080d1c'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, w, h); const verts = []; for (let i = 0; i < mesh.positions.length; i += 3) { const p = projectPoint(mesh.positions[i], mesh.positions[i + 1], mesh.positions[i + 2]); verts.push({ x: w / 2 + (p.x - state.camera.panX) * scale, y: h / 2 - (p.y - state.camera.panY) * scale, d: p.depth, c: mesh.colors.slice(i, i + 3) }); } const tris = []; for (let i = 0; i < mesh.indices.length; i += 3) tris.push([verts[mesh.indices[i]], verts[mesh.indices[i + 1]], verts[mesh.indices[i + 2]]]); tris.sort((a, b) => (a[0].d + a[1].d + a[2].d) - (b[0].d + b[1].d + b[2].d)); tris.forEach(t => { const c = t[0].c.map(v => Math.round(v * 255)); ctx.beginPath(); ctx.moveTo(t[0].x, t[0].y); ctx.lineTo(t[1].x, t[1].y); ctx.lineTo(t[2].x, t[2].y); ctx.closePath(); ctx.fillStyle = `rgb(${c.join(',')})`; ctx.globalAlpha = .86; ctx.fill(); ctx.strokeStyle = 'rgba(255,255,255,.07)'; ctx.stroke(); }); ctx.globalAlpha = 1; }

render();
